apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::423705228235:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423705228235:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1PECXU2EKSUGR
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-02T16:51:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1243"
  uid: e20d7205-498d-4c88-9073-4b51743e1f61
