apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::423705228235:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423705228235:role/eksctl-simple-jwt-api2-nodegroup-NodeInstanceRole-1AJVEUNK63FRA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-05T20:16:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1200"
  uid: 9d562a4d-3556-47e2-aab5-0592527af70f
